In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('data/price_history_NABIL.csv')
df.head()

   id symbol        date   open   high    low   close  traded_quantity
0   1  NABIL  2025-09-28  524.0  528.0  521.0  527.00            30997
1   2  NABIL  2025-09-25  523.0  524.9  516.0  521.60            28626
2   3  NABIL  2025-09-24  525.0  528.0  515.0  522.00            59254
3   4  NABIL  2025-09-23  516.9  525.0  513.0  523.50            55373
4   5  NABIL  2025-09-21  474.0  514.0  474.0  510.18           122490

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3310 entries, 0 to 3309
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               3310 non-null   int64
 1   symbol           3310 non-null   object
 2   date             3310 non-null   object
 3   open             3310 non-null   float64
 4   high             3310 non-null   float64
 5   low              3310 non-null   float64
 6   close            3310 non-null   float64
 7   traded_quantity  3310 non-null   int64
dtypes: float64(4), int64(2), object(2)
memory usage: 207.0+ KB

In [4]:
df.describe()

,id,open,high,low,close,traded_quantity
count,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000,3310.000000
mean,1655.603927,1240.458426,1253.635166,1224.953353,1239.287737,33885.109366
std,955.820382,585.729774,593.556365,580.146574,587.662658,54156.306475
min,1.000000,421.100000,425.000000,419.000000,422.000000,24.000000
25%,828.250000,782.000000,785.000000,775.000000,779.000000,2666.750000
50%,1655.500000,1090.000000,1106.000000,1070.150000,1091.000000,8591.000000
75%,2482.750000,1718.000000,1730.000000,1700.000000,1718.000000,48084.000000
max,3311.000000,2720.000000,2800.000000,2700.000000,2750.000000,705430.000000

In [5]:
# while working upon timeseries always sort the date so that we can predict how it works with time


df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')
df.set_index('date', inplace = True)

In [6]:
df.columns

Index(['id', 'symbol', 'open', 'high', 'low', 'close', 'traded_quantity'], dtype='object')

In [7]:
# Select Target Variable

In [7]:
ts = df['close']

In [9]:
# EBL

In [10]:
!pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels) (1.26.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [10]:
from statsmodels.tsa.stattools import adfuller

result = adfuller(ts)
print("ADF Statistics: ", result[0])
print("p- value : ", result[1])

ADF Statistics:  -1.4055886700522275
p- value :  0.5795939265023212

In [8]:
ts_diff =ts.diff().dropna()

In [11]:
# from statsmodels.tsa.stattools import adfuller

result = adfuller(ts_diff)
print("ADF Statistics: ", result[0])
print("p- value : ", result[1])

# p-value = 0 means it is stationary series

ADF Statistics:  -30.56917403222062
p- value :  0.0

In [14]:
# . What the Augmented Dickey-Fuller (ADF) Test Does
# - The ADF test checks whether a time series has a unit root.
# - Null hypothesis (H₀): The series has a unit root → it is non-stationary.
# - Alternative hypothesis (H₁): The series is stationary (no unit root).
# - Stationarity means the mean, variance, and autocorrelation structure of the series do not change over time.
# Stationary means p-value close to 0 and non unit root

In [15]:
ts = df['close']
ts

date
2011-03-20    1170.00
2011-03-24    1153.00
2011-03-25    1174.00
2011-03-27    1147.00
2011-03-28    1132.00
               ...
2025-09-21     510.18
2025-09-23     523.50
2025-09-24     522.00
2025-09-25     521.60
2025-09-28     527.00
Name: close, Length: 3310, dtype: float64

In [16]:
ts_diff

date
2011-03-24   -17.00
2011-03-25    21.00
2011-03-27   -27.00
2011-03-28   -15.00
2011-03-29   -35.00
              ...
2025-09-21    27.18
2025-09-23    13.32
2025-09-24    -1.50
2025-09-25    -0.40
2025-09-28     5.40
Name: close, Length: 3309, dtype: float64

In [17]:
! pip install pmdarima

Requirement already satisfied: pmdarima in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (2.1.1)
Requirement already satisfied: joblib>=0.11 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (1.5.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (3.2.2)
Requirement already satisfied: numpy>=1.21.6 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (1.26.4)
Requirement already satisfied: pandas>=0.19 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (2.3.3)
Requirement already satisfied: scikit-learn>=0.22 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (1.7.2)
Requirement already satisfied: scipy>=1.13.0 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (1.15.3)
Requirement already satisfied: statsmodels>=0.14.5 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (0.14.6)
Requirement already satisfied: urllib3 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (2.5.0)
Requirement already satisfied: setuptools!=50.0.0,>=42 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (80.9.0)
Requirement already satisfied: packaging>=17.1 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pmdarima) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas>=0.19->pmdarima) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas>=0.19->pmdarima) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from pandas>=0.19->pmdarima) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.19->pmdarima) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from scikit-learn>=0.22->pmdarima) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\prash\anaconda3\envs\cnn\lib\site-packages (from statsmodels>=0.14.5->pmdarima) (1.0.2)

In [18]:
# Find ARIMA Order Automatically

# from statsmodels.tsa.arima_model import ARIMA
from pmdarima import auto_arima

stepwise_fit = auto_arima(ts, d = 1, trace = True, supress_warnings = True)
print(stepwise_fit.summary())

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=32719.027, Time=4.05 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=32764.604, Time=0.19 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=32733.167, Time=0.42 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=32729.065, Time=0.47 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=32762.711, Time=0.11 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=32718.252, Time=3.10 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=32723.684, Time=0.69 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=32726.586, Time=1.43 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=32719.553, Time=3.82 sec
 ARIMA(0,1,3)(0,0,0)[0] intercept   : AIC=32720.653, Time=0.87 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=32717.150, Time=1.85 sec
 ARIMA(2,1,0)(0,0,0)[0] intercept   : AIC=32721.609, Time=0.44 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=32719.083, Time=5.25 sec
 ARIMA(3,1,0)(0,0,0)[0] intercept   : AIC=32720.187, Time=0.66 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=32721.051, Time=2.59 sec
 ARIMA(2,1,1)(0,0,0)[0]             : AIC=32715.265, Time=0.90 sec
 ARIMA(1,1,1)(0,0,0)[0]             : AIC=32724.671, Time=0.69 sec
 ARIMA(2,1,0)(0,0,0)[0]             : AIC=32719.709, Time=0.27 sec
 ARIMA(3,1,1)(0,0,0)[0]             : AIC=32717.199, Time=1.45 sec
 ARIMA(2,1,2)(0,0,0)[0]             : AIC=32717.143, Time=1.79 sec
 ARIMA(1,1,0)(0,0,0)[0]             : AIC=32731.255, Time=0.21 sec
 ARIMA(1,1,2)(0,0,0)[0]             : AIC=32716.370, Time=1.12 sec
 ARIMA(3,1,0)(0,0,0)[0]             : AIC=32718.293, Time=0.35 sec
 ARIMA(3,1,2)(0,0,0)[0]             : AIC=32719.164, Time=1.39 sec

Best model:  ARIMA(2,1,1)(0,0,0)[0]
Total fit time: 34.123 seconds
                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 3310
Model:               SARIMAX(2, 1, 1)   Log Likelihood              -16353.633
Date:                Tue, 09 Dec 2025   AIC                          32715.265
Time:                        16:16:34   BIC                          32739.683
Sample:                             0   HQIC                         32724.004
                               - 3310
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.6415      0.105      6.114      0.000       0.436       0.847
ar.L2         -0.1191      0.011    -10.396      0.000      -0.142      -0.097
ma.L1         -0.5378      0.106     -5.094      0.000      -0.745      -0.331
sigma2      1149.6969      4.853    236.899      0.000    1140.185    1159.209
===================================================================================
Ljung-Box (L1) (Q):                   0.00   Jarque-Bera (JB):            667984.42
Prob(Q):                              0.98   Prob(JB):                         0.00
Heteroskedasticity (H):               0.13   Skew:                            -4.24
Prob(H) (two-sided):                  0.00   Kurtosis:                        72.09
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [19]:
# pmdarima is used to select the best ARIMA model

In [23]:
from statsmodels.tsa.arima.model import ARIMA

In [24]:
model = ARIMA(ts_diff, order = (2,1,1))
model_fit = model.fit()
print(model_fit.summary())

c:\Users\prash\anaconda3\envs\cnn\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\prash\anaconda3\envs\cnn\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
c:\Users\prash\anaconda3\envs\cnn\lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)

                               SARIMAX Results
==============================================================================
Dep. Variable:                  close   No. Observations:                 3309
Model:                 ARIMA(2, 1, 1)   Log Likelihood              -16356.366
Date:                Tue, 09 Dec 2025   AIC                          32720.731
Time:                        16:18:41   BIC                          32745.148
Sample:                             0   HQIC                         32729.470
                               - 3309
Covariance Type:                  opg
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1          0.1070      0.010     10.886      0.000       0.088       0.126
ar.L2         -0.0637      0.012     -5.327      0.000      -0.087      -0.040
ma.L1         -1.0000      0.043    -23.281      0.000      -1.084      -0.916
sigma2      1151.3467     47.886     24.043      0.000    1057.491    1245.202
===================================================================================
Ljung-Box (L1) (Q):                   0.02   Jarque-Bera (JB):            686551.39
Prob(Q):                              0.90   Prob(JB):                         0.00
Heteroskedasticity (H):               0.13   Skew:                            -4.33
Prob(H) (two-sided):                  0.00   Kurtosis:                        73.04
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [26]:
import joblib


joblib.dump(model, "nabil_arima_model.pkl")

['nabil_arima_model.pkl']

In [ ]:
# p = AR(autoregressive order)

# d = differencing 🔂 

# q = MA(moving average order)